<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Handbook Example</title>
<link rel="stylesheet" type="text/css" href="css/view.css" media="all">
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript" src="view.js"></script>
<script type="text/javascript" src="template/handbook.js"></script>
</head>
<body id="main_body" >

	<?php include "controller/form.php"?>

	<div id='file_container'>
		<?php include 'template/handbook.php'?>
	</div>

	<img id="top" src="images/top.png" alt="">
	<div id="form_container">

		<h2><a>Handbook</a></h2>
		<form id="formExp" class="appnitro" method="post" action="">
					<div class="form_description">
			<h3>Example</h3>
		</div>
			<ul >
					<li id="li_1" >
			<input id="buffer" name="buffer" type="text" maxlength="255" style="visibility:hidden"/>
		<div>
			<input id="name" name="name" placeholder="Ad Soyad" class="element text medium" type="text" maxlength="255" required/>
		</div>
		</li>		<li id="li_2" >
		<div>
			<input id="email" name="email" placeholder="E-mail" class="element text medium" type="email" maxlength="255" required/>
		</div>
		</li>		<li id="li_3" >
		<div>
			<textarea id="address" name="address" placeholder="Adres" class="element textarea medium" required></textarea>
		</div>
		</li>
					<li class="buttons">
			    <input type="hidden" name="form_id" value="57760" />

				<input id="saveForm" class="button_text new" type="submit" name="submit" value="Gönder"	/>
				<input id="editForm" class="button_text" type="submit" name="edit" value="Düzenle"/>
				<input id="delForm" class="button_text" type="submit" name="delete" value="Sil"/>
				<input id="id" name="id" type="text" maxlength="255" style="visibility:hidden"/>
		</li>
			</ul>
		</form>
		<div id="footer">
			Generated by <a href="https://onuryarar.github.io">Onur Yarar</a>
		</div>
	</div>
	<img id="bottom" src="images/bottom.png" alt="">
	</body>
</html>